#!/usr/bin/bash
# SPDX-License-Identifier: Unlicense OR CC0-1.0
# Copyright © 2013-2021 Oliver Niebuhr, https://github.com/MeerMusik/LinuxDevelopment / https://oliverniebuhr.de / https://twitter.com/MeerMusik

# The Script Content was originally copied from an Example on the Internet.
# It was available for public use. Unfortunately, I forgot where I found it though. I am 99 percent sure it was on stackoverflow.com
# I am releasing the modified Script under The Unlicense OR CC0-1.0

# - CC0 1.0 Universal License Text Start -
# LinuxDevelopment - Scripts
# Written in 2013-2021 by Oliver Niebuhr, email: gitrepos@oliverniebuhr.de / Website: https://oliverniebuhr.de / Twitter: https://twitter.com/MeerMusik
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>
# - CC0 1.0 Universal License Text End -

# How to install this Script: Arch Linux based:
# 1.) Modify the Directory Names to match your Personal Directory Structure!
# 2.) Copy this File to: /usr/local/bin/
# 2.)A.) Example: sudo cp --verbose $HOME/Dev/GitRepos/LinuxDevelopment/python /usr/local/bin/
# 2.)B.) In case of Errors, try: Example: sudo cp --force --remove-destination --verbose $HOME/Dev/GitRepos/LinuxDevelopment/python /usr/local/bin/
# 3.) Make sure the Script has executable rights: sudo chmod u+x /usr/local/bin/python
script=$(readlink -f -- "$1")
case "$script" in ($HOME/Dev/Builds/Qtx86Debug/*|$HOME/Dev/Builds/Qtx86Release/*|$HOME/Dev/Builds/Qtx64Debug/*|$HOME/Dev/Builds/Qtx64Release/*)
    exec python2 "$@"
    ;;
esac

exec python3 "$@" 
