name: Question Form
description: As long as your Questions have to do with the Content in this Repository, they are considered on Topic.
title: "[Question]: "
labels: ['Type: Question']
assignees:
  - MeerMusik
body:
- type: markdown
  attributes:
    value: |
      This Issue will be public and can be read by anyone! Do not publish private Informations here!
- type: checkboxes
  id: author-has-read-and-agrees-to-follow-contribution-rules
  attributes:
    label: Contribution Rules
    description: By submitting this issue, you A.) confirm that you have read the [Contribution Rules](../blob/main/CONTRIBUTING.md) and B.) agree to follow them
    options:
    - label: I confirm that I have read the Contribution Rules and I agree to follow them
      required: true
- type: checkboxes
  id: author-has-read-and-agrees-to-follow-code-of-conduct
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you A.) confirm that you have read the [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md) and B.) agree to follow it
    options:
    - label: I confirm that I have read the Code of Conduct and I agree to follow it
      required: true
- type: checkboxes
  id: author-has-checked-issue-list
  attributes:
    label: Does an Issue already exist which do answer your Question?
    description: Please look at the existing Issues to make sure your Question does not already exist!
    options:
    - label: I have looked at the existing Issues. My Question does not exist or the detail I would like know about was not answered in a similar Question
      required: true
- type: textarea
  id: new-question
  attributes:
    label: Ask away!
    description: Ask whatever you want, as long as it has to do with the Content of this Repository!
    placeholder: Ask whatever you want, as long as it has to do with the Content of this Repository!
    value: "Ask whatever you want, as long as it has to do with the Content of this Repository!"
  validations:
    required: true
