#!/usr/bin/bash
# SPDX-License-Identifier: Unlicense OR CC0-1.0
# Copyright © 2021 Oliver Niebuhr, https://github.com/MeerMusik/LinuxScripts / https://oliverniebuhr.de / https://twitter.com/MeerMusik
# - CC0 1.0 Universal License Text Start -
# LinuxScripts
# Written in 2021 by Oliver Niebuhr, email: gitrepos@oliverniebuhr.de / Website: https://oliverniebuhr.de / Twitter: https://twitter.com/MeerMusik
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>
# - CC0 1.0 Universal License Text End -
if [ ! -d $HOME/Dev/ ]; then mkdir $HOME/Dev/
fi
if [ ! -d $HOME/Dev/Builds/ ]; then mkdir $HOME/Dev/Builds/
fi
if [ -d $HOME/Dev/Builds/wxWidgetsx64/ ]; then rm --interactive=never --dir --recursive --force --verbose $HOME/Dev/Builds/wxWidgetsx64/*.* $HOME/Dev/Builds/wxWidgetsx64/* $HOME/Dev/Builds/wxWidgetsx64/
fi
if [ ! -d $HOME/Dev/Builds/wxWidgetsx64/ ]; then cp --force --recursive --verbose $HOME/Dev/GitRepos/wxWidgets/ $HOME/Dev/Builds/wxWidgetsx64/
fi
cd $HOME/Dev/Builds/wxWidgetsx64/
cmake -G'Ninja' . -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCOTIRE_VERBOSE=ON -DCMAKE_C_FLAGS='-D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fcf-protection=branch -finput-charset=utf-8 -fno-lto -fno-omit-frame-pointer -fPIE -pie -ftrapv -frecord-gcc-switches -grecord-gcc-switches -mfunction-return=thunk -mindirect-branch=thunk -mindirect-branch-register -pthread -Og -ggdb3 -static-libgcc -static-libstdc++ -static-pie -pipe -std=c2x -Wall -Walloc-zero -Wcast-align -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-overflow=2 -Wformat-security -Wformat-truncation -Wimplicit-fallthrough -Wlogical-op -Wmisleading-indentation -Wmissing-declarations -Wnonnull -Wnull-dereference -Wpedantic -Wpointer-arith -Wshadow -Wsign-conversion -Wstrict-overflow -Wtrampolines -Wunused -Wvla -Wl,--pic-executable -Wl,-Og -Wl,--allow-multiple-definition -Wl,--build-id=sha1 -Wl,--discard-locals -Wl,-fno-lto -Wl,-z,relro -Wl,-z,now' -DCMAKE_CXX_FLAGS='-D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fcf-protection=branch -finput-charset=utf-8 -fno-lto -fno-omit-frame-pointer -fPIE -pie -fstack-protector-all -ftrapv -frecord-gcc-switches -grecord-gcc-switches -mfunction-return=thunk -mindirect-branch=thunk -mindirect-branch-register -pthread -Og -ggdb3 -static-libgcc -static-libstdc++ -static-pie -pipe -std=c++20 -Wall -Walloc-zero -Wcast-align -Wclass-memaccess -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-overflow=2 -Wformat-security -Wformat-truncation -Wimplicit-fallthrough -Wlogical-op -Wmisleading-indentation -Wmissing-declarations -Wnonnull -Wnon-virtual-dtor -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wpointer-arith -Wreorder -Wshadow -Wsign-conversion -Wstrict-overflow -Wtrampolines -Wunused -Wuseless-cast -Wvla -Wl,--pic-executable -Wl,-Og -Wl,--allow-multiple-definition -Wl,--build-id=sha1 -Wl,--discard-locals -Wl,-fno-lto -Wl,-z,relro -Wl,-z,now' -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/Dev/Binaries/wxWidgetsx64Debug/ -DwxBUILD_COMPATIBILITY=3.1 -DwxBUILD_CXX_STANDARD=20 -DwxBUILD_DEBUG_LEVEL=2 -DwxBUILD_DEMOS=OFF -DwxBUILD_INSTALL=ON -DwxBUILD_MONOLITHIC=OFF -DwxBUILD_OPTIMISE=OFF -DwxBUILD_PIC=ON -DwxBUILD_PRECOMP=ON -DwxBUILD_SAMPLES=OFF -DwxBUILD_SHARED=OFF -DwxUSE_REPRODUCIBLE_BUILD=OFF -DwxBUILD_TESTS=OFF -DwxBUILD_TOOLKIT=gtk3 -DwxBUILD_USE_STATIC_RUNTIME=ON -DwxUSE_EXCEPTIONS=1 -DwxNO_UNSAFE_WXSTRING_CONV=1 -DwxUSE_DEBUG_CONTEXT=1 -DwxUSE_MEMORY_TRACING=1 -DxUSE_GLOBAL_MEMORY_OPERATORS=1 -DwxUSE_DEBUG_NEW_ALWAYS=1
ninja --verbose -j -k 1
ninja -j1 install
ninja --verbose clean
rm --interactive=never --force --verbose $HOME/Dev/Builds/wxWidgetsx64/CMakeCache.txt
cmake -G'Ninja' . -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCOTIRE_VERBOSE=ON -DCMAKE_C_FLAGS='-D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fcf-protection=branch -finput-charset=utf-8 -fno-lto -fno-omit-frame-pointer -fPIE -pie -ftrapv -frecord-gcc-switches -grecord-gcc-switches -mfunction-return=thunk -mindirect-branch=thunk -mindirect-branch-register -pthread -Os -g1 -static-libgcc -static-libstdc++ -static-pie -pipe -std=c2x -Wall -Walloc-zero -Wcast-align -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-overflow=2 -Wformat-security -Wformat-truncation -Wimplicit-fallthrough -Wlogical-op -Wmisleading-indentation -Wmissing-declarations -Wnonnull -Wnull-dereference -Wpedantic -Wpointer-arith -Wshadow -Wsign-conversion -Wstrict-overflow -Wtrampolines -Wunused -Wvla -Wl,--pic-executable -Wl,-Os -Wl,--allow-multiple-definition -Wl,--build-id=sha1 -Wl,--discard-locals -Wl,-fno-lto -Wl,-z,relro -Wl,-z,now' -DCMAKE_CXX_FLAGS='-D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fasynchronous-unwind-tables -fexceptions -fcf-protection=branch -finput-charset=utf-8 -fno-lto -fno-omit-frame-pointer -fPIE -pie -fstack-protector-all -ftrapv -frecord-gcc-switches -grecord-gcc-switches -mfunction-return=thunk -mindirect-branch=thunk -mindirect-branch-register -pthread -Os -g1 -static-libgcc -static-libstdc++ -static-pie -pipe -std=c++20 -Wall -Walloc-zero -Wcast-align -Wclass-memaccess -Wconversion -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wextra -Wformat=2 -Wformat-nonliteral -Wformat-overflow=2 -Wformat-security -Wformat-truncation -Wimplicit-fallthrough -Wlogical-op -Wmisleading-indentation -Wmissing-declarations -Wnonnull -Wnon-virtual-dtor -Wnull-dereference -Wold-style-cast -Woverloaded-virtual -Wpedantic -Wpointer-arith -Wreorder -Wshadow -Wsign-conversion -Wstrict-overflow -Wtrampolines -Wunused -Wuseless-cast -Wvla -Wl,--pic-executable -Wl,-Os -Wl,--allow-multiple-definition -Wl,--build-id=sha1 -Wl,--discard-locals -Wl,-fno-lto -Wl,-z,relro -Wl,-z,now' -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_INSTALL_PREFIX=$HOME/Dev/Binaries/wxWidgetsx64Release/ -DwxBUILD_COMPATIBILITY=3.1 -DwxBUILD_CXX_STANDARD=20 -DwxBUILD_DEBUG_LEVEL=1 -DwxBUILD_DEMOS=OFF -DwxBUILD_INSTALL=ON -DwxBUILD_MONOLITHIC=OFF -DwxBUILD_OPTIMISE=OFF -DwxBUILD_PIC=ON -DwxBUILD_PRECOMP=ON -DwxBUILD_SAMPLES=OFF -DwxBUILD_SHARED=OFF -DwxUSE_REPRODUCIBLE_BUILD=OFF -DwxBUILD_TESTS=OFF -DwxBUILD_TOOLKIT=gtk3 -DwxBUILD_USE_STATIC_RUNTIME=ON -DwxUSE_EXCEPTIONS=1 -DwxNO_UNSAFE_WXSTRING_CONV=1
ninja --verbose -j -k 1
ninja -j1 install
cd $HOME
echo Script paused for 10 Seconds to be able to read the build Results! Please wait a moment...
sleep 10s
rm --interactive=never --dir --recursive --force --verbose $HOME/Dev/Builds/wxWidgetsx64/*.* $HOME/Dev/Builds/wxWidgetsx64/* $HOME/Dev/Builds/wxWidgetsx64/
echo DONE!
exit
